# Generated by Django 5.2.5 on 2025-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.SmallIntegerField(default=0, verbose_name='Колличество просмотров'),
        ),
    ]
